//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRISWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tappDFlexiblesLog
    {
        public int Id { get; set; }
        public string EIC { get; set; }
        public string loginStatus { get; set; }
        public System.DateTime timeStamp { get; set; }
    }
}
