//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRISWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tappSalarySchem
    {
        public int recNo { get; set; }
        public string paySchemeCode { get; set; }
        public string paySchemeAcronym { get; set; }
        public string paySchemeName { get; set; }
    }
}
