//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRISWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tappEmployee
    {
        public int recNo { get; set; }
        public string idNo { get; set; }
        public string EIC { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string middleName { get; set; }
        public string extName { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string birthplace { get; set; }
        public string fullnameFirst { get; set; }
        public string fullnameLast { get; set; }
        public Nullable<int> gender { get; set; }
        public string prefixTitle { get; set; }
        public string sufixTitle { get; set; }
    }
}
