//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRISWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tappEmpStatu
    {
        public int recNo { get; set; }
        public string statusCode { get; set; }
        public string statusName { get; set; }
        public Nullable<int> groupID { get; set; }
        public Nullable<int> isGovService { get; set; }
        public Nullable<int> isPlantilla { get; set; }
        public string @class { get; set; }
    }
}
