//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRISWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tappPositionSub
    {
        public int recNo { get; set; }
        public string subPositionCode { get; set; }
        public string positionCode { get; set; }
        public string subPositionName { get; set; }
        public string shortPositionName { get; set; }
        public string accronym { get; set; }
    }
}
