//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRISWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tappOffice
    {
        public int recNo { get; set; }
        public string officeCode { get; set; }
        public string officeName { get; set; }
        public string accronym { get; set; }
        public string officeServiceRec { get; set; }
        public string branch { get; set; }
        public Nullable<int> sortTag { get; set; }
        public Nullable<int> tagRemarks { get; set; }
    }
}
