//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRISWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tappPosition
    {
        public int recNo { get; set; }
        public string positionCode { get; set; }
        public string fullDescription { get; set; }
        public string shortDescription { get; set; }
        public string accronym { get; set; }
        public Nullable<int> sg { get; set; }
    }
}
