//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRISWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vJustifyApp
    {
        public int recNo { get; set; }
        public string controlNo { get; set; }
        public string EIC { get; set; }
        public string fullnameFirst { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string monthyear { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<int> logType { get; set; }
        public string logTitle { get; set; }
        public string time { get; set; }
        public string reason { get; set; }
        public string empGroupCode { get; set; }
        public string officeName { get; set; }
        public string approvingOfficer { get; set; }
        public Nullable<int> period { get; set; }
        public string approveEIC { get; set; }
        public Nullable<System.DateTime> timeIn1 { get; set; }
        public Nullable<System.DateTime> timeOut1 { get; set; }
        public Nullable<System.DateTime> timeIn2 { get; set; }
        public Nullable<System.DateTime> timeOut2 { get; set; }
        public Nullable<System.DateTime> logTime { get; set; }
        public Nullable<int> statusID { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> returnTag { get; set; }
    }
}
