//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRISWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vpassSlipApp
    {
        public int recNo { get; set; }
        public string controlNo { get; set; }
        public string EIC { get; set; }
        public string Date { get; set; }
        public Nullable<System.DateTime> timeOut { get; set; }
        public Nullable<System.DateTime> timeIn { get; set; }
        public string destination { get; set; }
        public string purpose { get; set; }
        public Nullable<int> isOfficial { get; set; }
        public Nullable<int> statusID { get; set; }
        public string fullnameFirst { get; set; }
        public string apprvEIC { get; set; }
        public string empGroupCode { get; set; }
        public Nullable<System.DateTime> In1 { get; set; }
        public Nullable<System.DateTime> Out1 { get; set; }
        public Nullable<System.DateTime> In2 { get; set; }
        public Nullable<System.DateTime> Out2 { get; set; }
        public Nullable<System.DateTime> outDate { get; set; }
    }
}
