//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRISWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPtlosName
    {
        public int recNo { get; set; }
        public string controlNo { get; set; }
        public string EIC { get; set; }
        public Nullable<int> statusID { get; set; }
        public string fullnameFirst { get; set; }
        public string designation { get; set; }
    }
}
